"""empty message

Revision ID: 383e623f150d
Revises: d6cae501cbfb
Create Date: 2023-04-24 15:43:25.574697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383e623f150d'
down_revision = 'd6cae501cbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
